options:
  _accept_license:
    default: false
    description: |
      This otions is mandatory.
      You have to accept the OpenDJ license terms before installation can proceed.
      The license terms can be found as part of the source in file named 'license.txt'.
    type: boolean
  _manager_password:
    description: |
      This options is mandatory.
      You have to provide a private OpenDJ 'Directory Manager' password before installation can proceed.
    type: string
    value: null
  ldap_port:
    type: int
    default: 389
    description: LDAP port
  base_dn:
    type: string
    default: "dc=example,dc=com"
    description: OpenDJ 'Base DN'.
  rest_enabled:
    default: false
    description: |
      Enabling the RESTful API for OpenDJ.
    type: boolean
  rest_port:
    type: int
    default: 8080
    description: RESTful API port.
  access_logging:
    default: false
    description: |
      Enabling HTTP Access logging for OpenDJ.
    type: boolean
