options:
  servername:
    type: string
    default: ''
    description: ServerName for vhost, defaults to the units public-address
  default_port:
    type: int
    default: 80
  vhost_http_template:
    type: string
    default: ''
    description: Apache vhost template (base64 encoded).
  vhost_https_template:
    type: string
    default: ''
    description: Apache vhost template (base64 encoded).
  enable_modules:
    type: string
    default: ''
    description: List of modules to enable
  disable_modules:
    type: string
    default: 'status autoindex'
    description: List of modules to disable
  config_change_command:
    type: string
    default: "reload"
    description: |
       The command to run whenever config has changed. Accepted values are
       "reload" or "restart" - any other value will mean neither is executed
       after a config change (which may be desired, if you're running a
       production server and would rather handle these out of band). Note:
       some variables like the mpm settings require a restart to go into effect.
  mpm_type:
    type: string
    default: 'worker'
    description: worker or prefork
  ssl_keylocation:
    type: string
    default: ''
    description: |
        Name and location of ssl keyfile in charm/data directory.
        If not found, will ignore.  Basename of this file will be used
        as the basename of the key rooted at /etc/ssl/private.  Can
        be used in conjuntion with the ssl_key parameter to specify
        the key as a configuration setting.
  ssl_certlocation:
    type: string
    default: ''
    description: |
        Name and location of ssl certificate in charm/data directory.
        If not found, will ignore.  Basename of this file will be used
        as the basename of the cert rooted at /etc/ssl/certs.  Can
        be used in conjunction with the ssl_cert parameter to specify
        the cert as a configuration setting.
  ssl_chainlocation:
    type: string
    default: ''
    description: |
        Name and location of the ssl chain file.  Basename of this file
        will be used as the basename of the chain file rooted at
        /etc/ssl/certs.
  lb_balancer_timeout:
    type: int
    default: 60
    description: >
       How long the backends in mod_proxy_balancer will timeout, in seconds
  mpm_startservers:
    type: int
    default: 2
    description: Add desc
  mpm_minsparethreads:
    type: int
    default: 25
    description: Add desc
  mpm_maxsparethreads:
    type: int
    default: 75
    description: Add desc
  mpm_threadlimit:
    type: int
    default: 64
    description: Add desc
  mpm_threadsperchild:
    type: int
    default: 64
    description: Add desc
  mpm_serverlimit:
    type: int
    default: 128
    description: Add desc
  mpm_maxclients:
    type: int
    default: 2048
    description: Add desc
  mpm_maxrequestsperchild:
    type: int
    default: 0
    description: Add desc
  nagios_context:
    default: "juju"
    type: string
    description: >
        Used by the nrpe-external-master subordinate charm.
        A string that will be prepended to instance name to set the host name
        in nagios. So for instance the hostname would be something like:
            juju-postgresql-0
        If you're running multiple environments with the same services in them
        this allows you to differentiate between them.
  nagios_check_http_params:
     default: ""
     type: string
     description: The parameters to pass to the nrpe plugin check_http.
  logrotate_rotate:
    type: string
    description: daily, weekly, monthly, or yearly?
    default: "daily"
  logrotate_count:
    type: int
    description: The number of days we want to retain logs for
    default: 365
  logrotate_dateext:
    type: boolean
    description: >
      Use daily extension like YYYMMDD instead of simply adding a number
    default: True
  package_status:
    default: "install"
    type: "string"
    description: >
      The status of service-affecting packages will be set to this value in the dpkg database.
      Useful valid values are "install" and "hold".
  use_rsyslog:
    type: boolean
    description: >-
      Change logging behaviour to log both access and error logs via rsyslog
    default: False
  ssl_cert:
    type: string
    description: |
        base64 encoded server certificate.  If the keyword 'SELFSIGNED'
        is used, the certificate and key will be autogenerated as
        self-signed.
    default: ''
  ssl_key:
    type: string
    description: |
        base64 encoded server certificate key.  If ssl_cert is
        specified as SELFSIGNED, this will be ignored.
    default: ''
  ssl_chain:
    type: string
    description: |
        base64 encoded chain certificates file.  If ssl_cert is
        specified as SELFSIGNED, this will be ignored.
    default: ''
  server_tokens:
    type: string
    description: Security setting. Set to one of  Full  OS  Minimal  Minor  Major  Prod
    default: "OS"
  server_signature:
    type: string
    description: Security setting. Set to one of  On  Off  EMail
    default: "On"
  trace_enabled:
    type: string
    description: Security setting. Set to one of  On  Off  extended
    default: "On"
  extra_packages:
    type: string
    description: List of extra packages to be installed (e.g. commercial GeoIP package)
    default: ""
  openid_provider:
    type: string
    description: Comma seperated list of OpenID providers for authentication.
    default: ""
